### PR TITLE
Add Cyberyen.

### PR DESCRIPTION
**Pull request by cymich**

### CODE REVIEW

**Comment by dangershony** [comment]
Do you have a fullnode? I don't think there is one in blockcore.

**Comment by dangershony** [comment]
the reason I ask is that normally in order to add a coin to this repo we expect to have a corresponding network in our fullnode repo.
FYI you can deploy the explorer/indexer without using this repo by just providing a custom settings file to the indexer/exporer.

@sondreb what is your opinion on this?

**Comment by sondreb** [comment]
We can add it and try to run it, but not sure if we can provide free hosting of wallet API, indexing API, block explorer, etc. If you host the indexing API yourself, we can include it in our explorer so users can find it through the multi-explorer.

**Review by sondreb — APPROVED** [review]
Thanks for this addition!

**Pull request merged**
