### PR TITLE
 update cybits and home logo

### PR DESCRIPTION
**Pull request by miladsoft**

### CODE REVIEW

**Review by dangershony — APPROVED** [review]
Looks good to me

**Comment by sondreb** [comment]
Where did you get the Home logo?

**Review by miladsoft — COMMENTED** [review]
Resized.

**Comment by psavva** [comment]
Hi @sondreb 
This is the official logo we will be using going forward (it's also the same in our blockcore-hub under assets/cybits)

**Review by sondreb — COMMENTED** [review]
Thanks!

**Comment by miladsoft** [comment]
Thanks @sondreb

**Pull request merged**
